export const EXTRACT_ID_FROM_NOTE = "EXTRACT_ID_FROM_NOTE";
export const CHECK_ALL = "CHECK_ALL";
export const TOGGLE_EDIT_MODE = "TOGGLE_EDIT_MODE";
export const TOGGLE_NOTE = "TOGGLE_NOTE";
export const TOGGLE_ACTIVE_NOTE = "TOGGLE_ACTIVE_NOTE";
export const CHANGE_CATEGORY_EDITMODE = "CHANGE_CATEGORY_EDITMODE";
